PROG=clirc
OBJS=rc-switch/RCSwitch.o main.o

LDLIBS=-lwiringPi

CXXFLAGS+=-DRPI

ifdef DEFAULT_SENDPIN
CXXFLAGS+=-DDEFAULT_SENDPIN=$(DEFAULT_SENDPIN)
endif

ifdef DEFAULT_RETRANSMIT
CXXFLAGS+=-DDEFAULT_RETRANSMIT=$(DEFAULT_RETRANSMIT)
endif

ifdef DEFAULT_PULSELENGTH
CXXFLAGS+=-DDEFAULT_PULSELENGTH=$(DEFAULT_PULSELENGTH)
endif

all: $(PROG)

$(PROG): $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $+ -o $@ $(LDLIBS)

clean:
	rm -f $(PROG) *.o rc-switch/*.o
